config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :base_images
  resources :captioned_images do
    get :preview, on: :collection
    delete :discard, on: :member
  end
end

app/models/base_image.rb
class BaseImage < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/caption.rb
class Caption < ActiveRecord::Base
  def text
    line2.blank? ? line1 : line1 + "\n" + line2
  end
end

app/models/captioned_image.rb
class CaptionedImage < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user
end

app/models/image_generator.rb
require "rmagick"

class ImageGenerator < ActiveRecord::Base
  def self.generate(image_url, text)
    img = Magick::Image.read(image_url).first
    #canvas = Magick::Image.new(350, 350)

    draw = Magick::Draw.new
    draw.align = Magick::CenterAlign

    draw.annotate(img, 512, 512, 256, 450, text) do
      self.font = 'public/uploads/SimHei.ttf'
      self.pointsize = 48
      #self.font_weight = Magick::NormalWeight
      self.font_weight = Magick::BoldWeight
      self.fill = 'black'
      self.gravity = Magick::SouthEastGravity
      self.stroke = "white"
    end

    # result_image = canvas.to_blob { self.format = 'gif' }
    img.write('public/uploads/images/test.jpg')
  end

  private

  def self.image(image_url)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :captioned_images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/base_images_controller.rb
class BaseImagesController < ApplicationController
  def index
    @base_images = BaseImage.all.order('created_at DESC')
  end

  def create
    @base_image = BaseImage.create!(image: params[:file])
    render :text => :success
  end

  def show
    @base_image = BaseImage.find(params[:id])
  end
end

app/controllers/captioned_images_controller.rb
class CaptionedImagesController < ApplicationController
  def new
    @captioned_image = CaptionedImage.new
    @base_image = BaseImage.find(params[:base_image_id])
    @captions = Caption.all
  end

  def preview
    @base_image = BaseImage.find(params[:base_image_id])
    @caption = Caption.find(params[:caption_id])
    @captioned_image = ImageProcessor.caption_image(@base_image, @caption, nil)
  end

  def submit
    redirect_to :root
  end

  def discard
    CaptionedImage.find(params[:id]).destroy!
    redirect_to new_captioned_image_path(base_image_id: params[:base_image_id])
  end

  def show
    @base_image = BaseImage.find(params[:id])
    #@captioned_image = CaptionedImage.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
  end

  def index
    render :index
  end

  def generate
    image_url = "public/uploads/faces/jgz-2.jpeg"
    text = "喂？是120吗？\n我太帅睡不着怎么办？"
    ImageGenerator.generate(image_url, text)
    redirect_to images_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @captioned_images = CaptionedImage.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/base_images/index.slim
.h10
.rows
  .dropzone-previews.col-xs-4.hidden.base_img_box
  - @base_images.each do |img|
    .col-xs-4.base_img_box
      = link_to new_captioned_image_path(base_image_id: img.id) do
        = image_tag img.image.url

app/views/base_images/show.slim
= image_tag @base_image.image.url

app/views/captioned_images/new.slim
= image_tag 'block.png', class: 'captioning-img-bg'
= image_tag @base_image.image.url, class: 'captioning-img'
- 4.times.each do |t|
  = link_to preview_captioned_images_path(base_image_id: @base_image.id, caption_id: @captions[t].id)
    - caption = @captions[t]
    .caption.pull-left id="caption#{t+1}"
      .caption-text class="#{caption.line2.present? ? 'twoline' : 'oneline'}"
        = caption.line1
        br
        - if caption.line2.present?
          = caption.line2

app/views/captioned_images/preview.slim
= image_tag 'block.png', class: 'captioning-img-bg'
= image_tag @captioned_image.image.url, class: 'captioning-img'
= link_to root_path do
  .publish
    span.publish-text 发布

= link_to discard_captioned_image_path(@captioned_image, base_image_id: @base_image.id), method: :delete do
  .redo
    span 重来一遍

app/views/captioned_images/show.slim
= image_tag 'block.png', class: 'captioning-img-bg'
= image_tag @base_image.image.url, class: 'captioning-img'
= link_to root_path do
  .publish
    span.publish-text 发布

= link_to discard_caption_image_path, method: :delete do
  .redo
    span 重来一遍

app/views/images/index.slim
= image_tag "/uploads/images/test.jpg", style: 'width: 100%'
= image_tag "/uploads/images/test.jpg", style: 'width: 100%'

app/views/layouts/_footer.slim
= image_tag 'user.png', class: 'img-circle pull-left',
  style: "width: 110px; height: 110px; z-index: 99;position: absolute;bottom: 10px; left: 5px;"
#footer
  span.username 机智的豆子
  - if current_page?(root_path)
    = link_to base_images_path, class: "pull-right" do
      = image_tag 'addimg.png', class: 'footer-icon'
  - else
    = link_to :back, class: "pull-right" do
      = image_tag 'back.png', class: 'footer-icon'

  - if current_page?(base_images_path)
    = form_for BaseImage.new, url: base_images_path, remote: true, html: {class: 'dropzone pull-right'} do |f|
      .fallback
        = f.file_field :image, value: 'test'
      .dz-message
        = image_tag 'imgupload.png', class: 'footer-icon'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header style="background-color: #7ec8e3; height: 60px; color: white"
      /button.pull-left.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = image_tag "menu.png", class: 'pull-left'
      = image_tag "refresh.png", class: 'pull-right', onclick: 'window.location.reload();'
      .center
        = link_to '糊脸', root_path, class: 'navbar-brand logo'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        /== render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Match'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Match'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
      == render 'layouts/messages'
    .pd-header#main
      == yield
      .pd-footer
    = render "layouts/footer"

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.slim
- @captioned_images.each do |img|
  .img-wrap
    .border-bar
      .title.pull-left BigDou
      .pull-right.small 1天前
    .img-inner
      = image_tag img.image.url, class: "imgbox"
    .border-bar
      = image_tag "like-h.png"
      = image_tag "fa-h.png"